name: Build and Deploy to Render

on:
  push:
    branches:
      - main  # O workflow será executado sempre que houver um push na branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Clona o repositório

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'  # Especifique a versão do Node.js (ajuste conforme necessário)

    - name: Install dependencies with Yarn
      run: cd ./api && yarn install  # Instala as dependências na pasta "api"

    - name: Run tests with Yarn
      run: cd ./api && yarn test  # Executa os testes dentro da pasta "api"
